repos:
# exclude: ^vendor/

# ---- isort ---- : Sort imports alphabetically, and automatically separated into sections and by type
- repo: https://github.com/pycqa/isort
  rev: 5.11.5
  hooks:
    - id: isort
      name: isort (python)
      args: ["--profile", "black"]

# ---- Pre-commit hooks ---- : Standard hook library
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  -   id: trailing-whitespace
  -   id: end-of-file-fixer
  -   id: check-yaml
  -   id: check-added-large-files
      args: ['--maxkb=200']
  -   id: detect-private-key
  -   id: check-case-conflict # check for files that would conflict in case-insensitive file systems.
  -   id: check-merge-conflict # check for files that contain merge conflict strings.

# ---- Black ---- :Automatic source code formatting
- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
  - id: black
    args: [--safe, --quiet]

# ---- Flake8 ----- Syntax check and some basic flake8
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.0.0
  hooks:
  - id: check-ast
  - id: check-json
  - id: pretty-format-json
    args: ['--autofix']
  - id: flake8
    args: ['--max-line-length=88', '--select=E401,E711,E712,E713,E714,E721,E722,E901,F401,F402,F403,F405,F631,F632,F633,F811,F812,F821,F822,F841,F901,W191,W291,W292,W293,W602,W603,W604,W605,W606']
