training_dir: ../data/training/training_data
training_img_dir: ../data/training/training_data/img
training_mask_dir: ../data/training/training_data/mask

validation_dir: ../data/training/validation_data
validation_img_dir: ../data/training/validation_data/img
validation_mask_dir: ../data/training/validation_data/mask

ramp_dir: ../data/training/ramp_bentiu_south_sudan
ramp_mask: ../data/training/ramp_bentiu_south_sudan/mask
ramp_img: ../data/training/ramp_bentiu_south_sudan/img

stacked_dir: ../data/training/stacked_arrays

json_dir: ../data/training/json_dir

models_dir: ../models
outputs_dir: ../data/outputs

camp_tiles_dir: ../data
footprints_dir: ../data/footprints
