training_dir: ../data/training_data
training_img_dir: ../data/training_data/img
training_mask_dir: ../data/training_data/mask

validation_dir: ../data/validation_data
validation_img_dir: ../data/validation_data/img
validation_mask_dir: ../data/validation_data/mask

ramp_dir: ../data/ramp_bentiu_south_sudan
ramp_mask: ../data/ramp_bentiu_south_sudan/mask
ramp_img: ../data/ramp_bentiu_south_sudan/img

stacked_dir: ../data/stacked_arrays
stacked_img_dir: ../data/stacked_arrays/img
stacked_mask_dir: ../data/stacked_arrays/mask

json_dir: ../data/json_dir

models_dir: ../models
outputs_dir: ../outputs

camp_tiles_dir: ../data/camp_tiles
footprints_dir: ../footprints

wip_bucket: ons-net-zero-analysis-prod-somalia-wip
review_bucket: ons-net-zero-analysis-prod-somalia-review
