name: somalia-gcp
dependencies:
  - python=3.10
  - geopandas
  - rasterio
  - Path
  - matplotlib
  - numpy
  - scikit-learn
  - jupytext=1.14
  - jupyter
  - python=3.10
  - tensorflow
  - Path
  - numpy
  - segmentation_models
  - keras
  - scikit-learn
